name: Packaging

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: "Build and Test"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'

      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

      - name: Vitest Coverage Report
        if: always() # Fixed placement of 'if'
        uses: davelosert/vitest-coverage-report-action@v2.8.0
        with:
          vite-config-path: vite-config.ts # Corrected the file name

  package-and-publish:
    needs: build
    name: 🐳 Package & Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 # Corrected the action version

      - name: Sign in to GitHub Container Registry
        uses: docker/login-action@v2 # Corrected the action version
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Generate Docker Metadata
        id: meta
        uses: docker/metadata-action@v4 # Corrected the action version
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=tag
            type=ref,event=pr
            type=sha,event=branch

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2 # Corrected the action version
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }} # Corrected key spelling from 'lables'
          cache-from: type=gha
          cache-to: type=gha,mode=max
